### ISSUE TITLE
github下载代码和maven下载代码运行效果不一致的问题

### ISSUE THREAD

**Issue by zZcoming** [hs-web/hsweb-expands#11]
同样是调用`ExcelIO.writeTemplate(inputStream, outputStream, var);`
debug调试到org.hswebframework.expands.script.engine.common.CommonScriptEngine的init方法的`ScriptEngine engine = manager.getEngineByName(getScriptName());`时，使用git clone的代码是能获取对象的，但是从maven下载的依赖获取的engine == null，不知道这是什么原因呢？这个导致NullPointException了

**Comment by zZcoming** [comment]
pom.xml是按照readme.md里配置的
```
    <!--pom.xml-->
     <dependency>
        <groupId>org.hswebframework</groupId>
        <artifactId>hsweb-expands-office</artifactId>
        <version>3.0.0-SNAPSHOT</version>
    </dependency>
    
      <repositories>
        <repository>
            <id>hsweb-nexus</id>
            <name>Nexus Release Repository</name>
            <url>http://nexus.hsweb.me/content/groups/public/</url>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
     </repositories>
```

**Comment by zhou-hao** [comment]
注意版本号。还有maven依赖的需要单独引入groovy



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: zZ丨 <notifications@github.com&gt;
发送时间: 2020年5月24日 23:41
收件人: hs-web/hsweb-expands <hsweb-expands@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[hs-web/hsweb-expands] github下载代码和maven下载代码运行效果不一致的问题 (#11)





 
同样是调用ExcelIO.writeTemplate(inputStream, outputStream, var);
 debug调试到org.hswebframework.expands.script.engine.common.CommonScriptEngine的init方法的ScriptEngine engine = manager.getEngineByName(getScriptName());时，使用git clone的代码是能获取对象的，但是从maven下载的依赖获取的engine == null，不知道这是什么原因呢？这个导致NullPointException了

**Comment by zZcoming** [comment]
十分感谢！修改hsweb-expands-office的版本号为3.0.3-SNAPSHOT，手动添加groovy依赖后能正常运行了。
```
<dependency>
    <groupId>org.codehaus.groovy</groupId>
    <artifactId>groovy-all</artifactId>
    <version>2.1.3</version>
</dependency>
```
就是不知道为什么hsweb-expands-office的pom.xml里要将groovy-all的optional设置为true呢，有什么讲究吗？

**Comment by zhou-hao** [comment]
有的地方可能用不上这个功能。毕竟groovy包也不小。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: zZ丨 <notifications@github.com&gt;
发送时间: 2020年5月25日 16:21
收件人: hs-web/hsweb-expands <hsweb-expands@noreply.github.com&gt;
抄送: 老周 <zh.sqy@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[hs-web/hsweb-expands] github下载代码和maven下载代码运行效果不一致的问题 (#11)





 
十分感谢！修改hsweb-expands-office的版本号为3.0.3-SNAPSHOT，手动添加groovy依赖后能正常运行了。
 <dependency&gt;     <groupId&gt;org.codehaus.groovy</groupId&gt;     <artifactId&gt;groovy-all</artifactId&gt;     <version&gt;2.1.3</version&gt; </dependency&gt;  
就是不知道为什么hsweb-expands-office的pom.xml里要将groovy-all的optional设置为true呢，有什么讲究吗？
