### ISSUE TITLE
export questito

### ISSUE THREAD

**Issue by huangzl08** [hs-web/hsweb-expands#2]
![image](https://cloud.githubusercontent.com/assets/19723199/23050996/a68f1464-f500-11e6-85c4-fe38586faf4e.png)

如果传过去是空值，却显示个获取参数，我希望如果是null值，然后就不显示

**Comment by zhou-hao** [comment]
感谢提交，下一步会优化一下

目前可以使用折中的办法:
1. 在传值前进行遍历替换null为空字符串
2. 表达式写成三目运算.${val==null?"":val}

**Comment by huangzl08** [comment]
thanks

**Comment by changdaye** [comment]
如果模版上有一个key  A  ， but 传值 没有key  A 会出现什么结果？

**Comment by zhou-hao** [comment]
@changdaye 应该会报错，找不到属性。

**Comment by changdaye** [comment]
@zhou-hao  那跟以前我们ftl做的一样， 没有key 就抛异常。。

**Comment by changdaye** [comment]
然并卵 这种还是html 去做比较好

**Comment by zhou-hao** [comment]
@changdaye  html不好控制样式，freemarker 编写模板不方便。

**Comment by changdaye** [comment]
@zhou-hao  html 直接丢给业务自己去写， freemarker编写模版确实不方便，  变量不存在问题怎么解决？

**Comment by zhou-hao** [comment]
@changdaye  我那个是提取变量，然后再填充。 提取变量后，判断传入的参数是否包含变量咯。不包含就设置一个默认值。 而且记得freemarker 不是可 ${val!''} 这样么。

**Comment by huangzl08** [comment]
@zhou-hao 还有，我想请问一下，如果我到处的word里三张表，但是如果有一张表，会根据不同情况而显示或隐藏，这功能能实现吗？

**Comment by zhou-hao** [comment]
@huangzl08 暂时没有这么丰富的功能额。 这种需求，还是找第三方提供支持吧。

**Comment by huangzl08** [comment]
如果有list,希望每一次循环,都生成一个新的表,这功能能实现吗?

**Comment by zhou-hao** [comment]
@huangzl08 循环生成多个表 暂时也不行的。。。

**Comment by huangzl08** [comment]
为什么我一执行循环生成表
public static void main(String[] args) throws Exception {
        String[] headers = {"姓名", "性别", "年龄", "班级"};
        List<Map<String, Object>> datas = new ArrayList<>();
        datas.add(new HashMap<String, Object>() {
            {
                put("姓名", "222");
                put("性别", "aaa");
            }
        });
        datas.add(new HashMap<String, Object>() {
            {
                put("姓名", "33");
                put("性别", "222");
            }
        });
        XWPFDocument document = new XWPFDocument();
        XWPFTable table = document.createTable(datas.size(), headers.length);
        table.setWidth(500);
        List<XWPFTableRow> rows = table.getRows();
        for (int i = 0; i < rows.size(); i++) {
            if (i == 0) continue;
            XWPFTableRow row = rows.get(i);
            List<XWPFTableCell> cells = row.getTableCells();
            for (int x = 0; x < cells.size(); x++) {
                String header = headers[x];
                if (i == 1)
                    cells.get(x).setText(header);
                else {
                    String text = String.valueOf(datas.get(i - 1).get(header));
                    cells.get(x).setText(text);
                }
            }
        }
        document.write(new FileOutputStream("/home/zhouhao/桌面/test2.docx"));
    }
就CPU就跳到100%，然后就不运行了

**Comment by huangzl08** [comment]
请问一下，怎样可以导出，因为用你给的代码， 好像导出不了（如下图）
![image](https://cloud.githubusercontent.com/assets/19723199/23120988/99167142-f799-11e6-8402-5731851fa776.png)

**Comment by zhou-hao** [comment]
@huangzl08  
你可以替换一下你之前发的代码部分
```java
  List<XWPFTableRow> rows = table.getRows();
            for (int i = 0; i < rows.size(); i++) {
                //if (i == 0) continue;
                XWPFTableRow row = rows.get(i);
                List<XWPFTableCell> cells = row.getTableCells();
                for (int x = 0; x < cells.size(); x++) {
                    String header = headers[x];
                    if (i == 0)
                        cells.get(x).setText(header);
                    else {
                        String text = String.valueOf(datas.get(i).get(header));
                        cells.get(x).setText(text);
                    }
                }
            }
```

**Comment by huangzl08** [comment]
不好意思，我又有问题，因为如果有些空值它自动填充为 "null"，这有没有办法解决，还有，其实我最想的是：在模板中能不能像execl一样，直接用下面这种方式呢
 for (int i = 0; i < 20; i++) {
            final int t = i;
            datas.add(new HashMap<String, Object>() {
                {
                    put("grade", "一年级");
                    put("classes", "2班");
                    put("sex", "男");
                    put("name", "张三" + t);
                    put("age", t);
                    put("remark", "测试2");
                }
            });
}

**Comment by zhou-hao** [comment]
@huangzl08 单个表格可以使用excel模版的循环方式。只是不能循环生成对个表格。对于null的问题。可以通过重写map的get方法返回空字符串就行

**Comment by huangzl08** [comment]
我想问问：table.setWidth(500);      中这一好像超过1000，就没什么变化，而且，我想问，能不能那些标题能不能换行显示（现在那些标题 竖起来看起来好别扭）：
![image](https://cloud.githubusercontent.com/assets/19723199/23202720/3ee328d2-f91a-11e6-92bf-b9c3ab87813e.png)

**Comment by zhou-hao** [comment]
@huangzl08 不太清楚。你看一下poi的api吧。记得单元格可以设置段落格式的

**Comment by huangzl08** [comment]
还有，如果我导出word中，有多张表，有些表可能有好多条记录（即List），但是我又不想用 vars.put("list", new ArrayList<Object>() 这个办法（因为我有很多表，如果Object的话会有很多参数），那我因为怎么写

**Comment by zhou-hao** [comment]
#huangzl08 不是很明白你的目的。 多张表多个list? 你可以建个循环 put.。如:
```java
 for(....){ 
vars.put("list"+i,datas[i]) 
}
```

**Comment by huangzl08** [comment]
@zhou-hao 能加个Q不？我的QQ：602122328

**Comment by wsj2929** [comment]
如果我导出的word里三张表，但是如果有一张表，会根据不同情况而显示或隐藏，这功能能实现吗？

**Comment by zhou-hao** [comment]
这个要看对应的是excel的什么功能

发自我的iPhone


------------------ Original ------------------
From: wsj2929 ***@***.***&gt;
Date: Wed,Jul 13,2022 11:03 AM
To: hs-web/hsweb-expands ***@***.***&gt;
Cc: 老周 ***@***.***&gt;, State change ***@***.***&gt;
Subject: Re: [hs-web/hsweb-expands] export questito (#2)





 
如果我导出的word里三张表，但是如果有一张表，会根据不同情况而显示或隐藏，这功能能实现吗？

**Comment by wsj2929** [comment]
像这样的word文件，表格2根据条件做显示或隐藏，可以做到吗？用的是docx文件的模板{{#表格1}}，{{#表格2}}，{{#表格3}}






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hs-web/hsweb-expands"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月11日(星期二) 下午4:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hs-web/hsweb-expands] export questito (#2)





 这个要看对应的是excel的什么功能 
 
 发自我的iPhone 
 
 
 ------------------ Original ------------------ 
 From: wsj2929 ***@***.***&amp;gt; 
 Date: Wed,Jul 13,2022 11:03 AM 
 To: hs-web/hsweb-expands ***@***.***&amp;gt; 
 Cc: 老周 ***@***.***&amp;gt;, State change ***@***.***&amp;gt; 
 Subject: Re: [hs-web/hsweb-expands] export questito (#2) 
 
 
 
 
 
   
 如果我导出的word里三张表，但是如果有一张表，会根据不同情况而显示或隐藏，这功能能实现吗？
