### ISSUE TITLE
exl 根据模板导出报错    用的是测试例子

### ISSUE THREAD

**Issue by zhangxianweihebei** [hs-web/hsweb-expands#3]
![image](https://cloud.githubusercontent.com/assets/15844529/23299018/e014c46c-faba-11e6-830b-e3b904f32b28.png)

**Comment by zhou-hao** [comment]
你好，我这里测试是正常的。是用的官方默认的例子么？
![image](https://cloud.githubusercontent.com/assets/7791838/23299636/464cdb46-fabd-11e6-9fad-148482d005d6.png)

**Comment by zhangxianweihebei** [comment]
使用的官网例子

**Comment by zhangxianweihebei** [comment]
是不是 依赖  什么jar

**Comment by zhou-hao** [comment]
@zhangxianweihebei  你可以看一下官方的依赖

**Comment by zhangxianweihebei** [comment]
好的

**Comment by zZcoming** [comment]
我也是这个错，debug找到最后是`GrooyEngine.init()`第50行`manager.getEngineByName(getScriptName())`的返回为null。
我的运行环境跟例子中有点不同，因为在http://nexus.hsweb.me/content/groups/public/没有找到hsweb-expands-office的1.0.1版本，于是用的version是1.0，连带地把ooxml-schemas的版本由1.1变成1.3，xmlbeans的版本由2.3.0变为2.6.0
不知是否是因为依赖的问题？但是hsweb-expands-office用1.0.1又确实报错“Missing artifact org.hsweb:hsweb-expands-office:jar:1.0.1”

**Comment by zhou-hao** [comment]
@zZcoming  引入如下依赖试试
```xml
   <dependency>
            <groupId>org.codehaus.groovy</groupId>
            <artifactId>groovy-all</artifactId>
   </dependency>
```

**Comment by zZcoming** [comment]
@zhou-hao 成功运行了，十分感谢
