### ISSUE TITLE
自定义Excel样式可以设置行高，但无法设置列宽

### ISSUE THREAD

**Issue by fengxiaopeng** [hs-web/hsweb-expands#4]
//自定义样式
        ExcelWriterConfig config = new ExcelWriterConfig(){

            @Override
            public CustomRowStyle getRowStyle(int row, String header) {
                //设置宽度，这个可以用
                return new CustomRowStyle(40);
            }

            @Override
            public CustomColumnStyle getColumnStyle(int column, String header) {
                //设置宽度，这个为啥不起作用???????????????
                return new CustomColumnStyle(8000);
            }
        };

**Comment by zhou-hao** [comment]
已修复,请更新或者使用 1.0.2版本，再测试一下试试

**Comment by fengxiaopeng** [comment]
ok，已解决，谢谢!
